name: vocalize
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.17.8
  audioplayers: ^6.1.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  avatar_glow: ^3.0.1
  speech_to_text: ^7.0.0
  http: ^1.2.2
  http_parser: ^4.1.2
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  clipboard: ^0.1.3
  share_plus: ^10.1.4

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
